package Ventanas;


import Clases.Conexion;
import Clases.HorasExtras;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Reymundo Tenorio
 */
public class Modificar_HorasExtras extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar_HorasExtras() {
        initComponents();
        this.setResizable(false);
        
        
         int MaxID = 0;
        
           
        try{
        resultado = Conexion.consulta("Select Max(ID_Trabajador) from [dbo].[Trabajador]");
        
        while(resultado.next()){
            MaxID = resultado.getInt(1);
        }
        }catch(SQLException ex){
            
        }
        
      
        
        ID_Trabajador = new int[MaxID+1];
        ID_Trabajador [0] = 0;
        int i = 1;
        
         try{
       resultado = Conexion.consulta("Select [ID_Trabajador],[Nombres_Trabajador],[Apellidos_Trabajador]"
                + "   from [dbo].[Trabajador] where [Estado_Trabajador] = 'Activo'");
         
        while(resultado.next()){
            
                     
            ID_Trabajador [i] = resultado.getInt(1);
            cmbNombre.addItem(resultado.getString(2).trim().concat(" ").concat(resultado.getString(3).trim()));
            i = i+1;
            
        }
        }catch(SQLException ex){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbNombre = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtHrs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Horas Extras");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 5, 8));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("No. Horas Extras");
        jPanel1.add(jLabel1);

        txtID.setEditable(false);
        jPanel1.add(txtID);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Trabajador");
        jPanel1.add(jLabel5);

        cmbNombre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        jPanel1.add(cmbNombre);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad de Horas Extras");
        jPanel1.add(jLabel6);
        jPanel1.add(txtHrs);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Horas Extras");
        jPanel1.add(jLabel7);

        jFecha.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(jFecha);
        jFecha.getDateEditor().getUiComponent().addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdFechaKeyTyped(evt);
            }
        });

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(585, 223));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     public void  jdFechaKeyTyped(KeyEvent e) {
         
        Toolkit.getDefaultToolkit().beep();
        e.consume();
        
        }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    ResultSet resultado;
    int [] ID_Trabajador;
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       String dia, mes, ano;

        Calendar c = new GregorianCalendar();

        dia = Integer.toString(c.get(Calendar.DATE));
        mes = Integer.toString(c.get(Calendar.MONTH)+1);
        ano = Integer.toString(c.get(Calendar.YEAR));

        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd-MM-yyyy");
        String strFecha =dia+"-"+mes+"-"+ano ;
        Date fechaa = null;
        try {

            fechaa = formatoDelTexto.parse(strFecha);


            jFecha.setMaxSelectableDate(fechaa);
            

        } catch (ParseException ex) {

            ex.printStackTrace();

        }
       
       
         
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String ID, Nombre, Salario;

Nombre = (String) cmbNombre.getSelectedItem();

int ID_Trab = 0;

int index = cmbNombre.getSelectedIndex();
ID_Trab = ID_Trabajador [index]; 

String Fecha = null;

if(jFecha.getDate()!=null){
            String formato = jFecha.getDateFormatString();
            Date date = jFecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            Fecha = String.valueOf(sdf.format(date));    
                      
        }

int Dia, Mes, Ano;

String DiaC = null, MesC = null, AnoC = null;
 int j=0;
    
  
    
     StringTokenizer FC = new StringTokenizer(Fecha, "-");
                  
     while(FC.hasMoreTokens()){
         
                  if(j==2){
                      AnoC = FC.nextToken();
                      break;
                  }
                  
                   if(j==1){
                      
                      MesC= FC.nextToken();
                      j++;
                    }
                         
                    if(j==0){
                      
                      DiaC = FC.nextToken();
                     j++;
                    }
                    
                     }
                   
     Dia = Integer.parseInt(DiaC);
     Mes = Integer.parseInt(MesC);
     Ano = Integer.parseInt(AnoC);
     
    String Horas;
    
    Horas = txtHrs.getText().trim();
    
    int HorasEx = Integer.valueOf(Horas);
     
     ID = txtID.getText().trim();
     
     int ID_H = Integer.valueOf(ID);

        HorasExtras.Modificar_Horas(ID_H, ID_Trab, HorasEx, Dia, Mes, Ano);
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

  public void setV(Ver_HrsExtras v) {
        this.v = v;
    }

    
    private Ver_HrsExtras v;
    
    
    public void Parametros(String ID, String Nombre, String Hrs, String Fecha) throws ParseException{
        
        txtID.setText(ID);
        cmbNombre.setSelectedItem(Nombre);
        txtHrs.setText(Hrs);
        
SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
          
Date FechaF = null;
try {

FechaF = formatoDelTexto.parse(Fecha);

} catch (ParseException ex) {
}

SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd-MM-yyyy");
Date FechaN = formatoDeFecha.parse(formatoDeFecha.format(FechaF));

jFecha.setDate(FechaN);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_HorasExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Modificar_HorasExtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHrs;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
