package Ventanas;


import Clases.Conexion;
import Clases.Trabajador;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Reymundo Tenorio
 */
public class Modificar_Trabajador extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar_Trabajador() {
        initComponents();
        this.setResizable(false); 
        
           int ID_Max = 0;
        
        try{
        resultado = Conexion.consulta("Select Max([ID_Cargo]) from [dbo].[Cargo]");
        
        while(resultado.next()){
            ID_Max = resultado.getInt(1);
        }
        }catch(SQLException ex){
            
        }
        
        ID_Cargo = new int [ID_Max+1];
        
        ID_Cargo [0] = 0;
        
        int j = 1;
       
        
  
   
         try{
        resultado = Conexion.consulta("Select [ID_Cargo],[NombreCargo] from [dbo].[Cargo]");
        
        while(resultado.next()){
            ID_Cargo [j] = resultado.getInt(1);
            cmbCargo.addItem(resultado.getString(2));
            j++;
        }
        }catch(SQLException ex){
            
        }
         
      
         
         try{
        resultado = Conexion.consulta("Select [NombreDepartamento] from [dbo].[Departamento]");
        
        while(resultado.next()){
            cmbDepartamento.addItem(resultado.getString(1));
        }
        }catch(SQLException ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtINSS = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTel = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rdFemenino = new javax.swing.JRadioButton();
        rdMasculino = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbAntiguedad = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Trabajador");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(11, 2, 5, 8));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("No. Trabajador");
        jPanel1.add(jLabel1);

        txtID.setEditable(false);
        jPanel1.add(txtID);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("No. INSS");
        jPanel1.add(jLabel5);

        try {
            txtINSS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtINSS);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6);
        jPanel1.add(txtNombres);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Apellidos");
        jPanel1.add(jLabel7);
        jPanel1.add(txtApellidos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("No. Cédula");
        jPanel1.add(jLabel8);

        try {
            txtCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCedula);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Teléfono");
        jPanel1.add(jLabel9);

        try {
            txtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtTel);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Sexo");
        jPanel1.add(jLabel10);

        buttonGroup1.add(rdFemenino);
        rdFemenino.setText("Femenino");
        jPanel3.add(rdFemenino);

        buttonGroup1.add(rdMasculino);
        rdMasculino.setText("Masculino");
        jPanel3.add(rdMasculino);

        jPanel1.add(jPanel3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Departamento");
        jPanel1.add(jLabel12);

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        jPanel1.add(cmbDepartamento);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Cargo");
        jPanel1.add(jLabel11);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>" }));
        cmbCargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCargoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbCargo);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Salario");
        jPanel1.add(jLabel13);

        txtSalario.setEditable(false);
        jPanel1.add(txtSalario);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Años de Antiguedad");
        jPanel1.add(jLabel14);

        cmbAntiguedad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jPanel1.add(cmbAntiguedad);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(566, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    ResultSet resultado;
    
    public void setV(Ver_Trabajador v) {
        this.v = v;
    }

    
    private Ver_Trabajador v;
    
    
    public void Parametros(String ID, String INSS, String Nombres, String Apellidos,
            String Cedula, String Tel, String Sexo, String Cargo, String Deparamento,
            String Salario, String Antiguedad){
        
        
        txtID.setText(ID);
        txtNombres.setText(Nombres);
        txtApellidos.setText(Apellidos);
        txtINSS.setText(INSS);
        txtCedula.setText(Cedula);
        txtTel.setText(Tel);
        cmbAntiguedad.setSelectedItem(Antiguedad);
        cmbCargo.setSelectedItem(Cargo);
        cmbDepartamento.setSelectedItem(Deparamento);
        txtSalario.setText(Salario);
        
        if("Femenino".equals(Sexo)){
            rdFemenino.setSelected(true);
        }
        else{
            rdMasculino.setSelected(true);
        }
        
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

int [] ID_Cargo;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String ID, NoINSS, Nombres, Apellidos, Cedula, Tel, Sexo, Cargo, Departamento, Salario, Antiguedad;
        
ID = txtID.getText().trim();
NoINSS = txtINSS.getText().trim();
Nombres = txtNombres.getText().trim();
Apellidos = txtApellidos.getText().trim();
Cedula = txtCedula.getText().trim();
Tel = txtTel.getText().trim();
Cargo = (String) cmbCargo.getSelectedItem();
Departamento = (String) cmbDepartamento.getSelectedItem();
Salario = txtSalario.getText().trim();
Antiguedad = (String) cmbAntiguedad.getSelectedItem();


if(rdFemenino.isSelected()){
    Sexo = "Femenino";
}
else{
    Sexo = "Masculino";
}

double SalMin = Double.valueOf(Salario);
int AniosAntiguedad = Integer.valueOf(Antiguedad);


int ID_Departamento = 0;


 try{
        resultado = Conexion.consulta("Select [ID_Departamento] from [dbo].[Departamento] where "
                + "[NombreDepartamento] = '"+Departamento+"'");
        
        while(resultado.next()){
       ID_Departamento =   resultado.getInt(1);
        }
        }catch(SQLException ex){
            
        }
 
 int ID_Cargo = 0;
 
 
 try{
        resultado = Conexion.consulta("Select [ID_Cargo] from [dbo].[Cargo] where "
                + "[NombreCargo] = '"+Cargo+"'");
        
        while(resultado.next()){
       ID_Cargo =   resultado.getInt(1);
        }
        }catch(SQLException ex){
            
        }
 
 double SalarioMinimo = 0;
 
  try{
        resultado = Conexion.consulta("Select [SalarioMin] from [dbo].[Cargo] where "
                + "[NombreCargo] = '"+Cargo+"'");
        
        while(resultado.next()){
       SalarioMinimo =   resultado.getDouble(1);
        }
        }catch(SQLException ex){
            
        }
  
  if(SalMin<SalarioMinimo){
      JOptionPane.showMessageDialog(this, "Salario Estipulado Menor al Salario Mínimo","Salario Mínimo", JOptionPane.ERROR_MESSAGE);
 return;
  }

 int ID_Trabajador = Integer.valueOf(ID);
 
 Trabajador.Modificar_Trabajador(ID_Trabajador, NoINSS, Cedula, Nombres, Apellidos, Sexo, Tel, ID_Cargo, SalMin, AniosAntiguedad, ID_Departamento);
  
 this.v.MostrarTodo();
  this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbCargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCargoItemStateChanged
  int index = cmbCargo.getSelectedIndex();
        double Salario = 0;
        try{
    resultado = Conexion.consulta("Select [SalarioMin] from [dbo].[Cargo] "
            + " where [ID_Cargo] = "+ID_Cargo[index]);
          
    
    while(resultado.next()){
         Salario = resultado.getDouble(1);
    }
    }catch(SQLException ex){
               
        
            }
        
        txtSalario.setText(String.valueOf(Salario));        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCargoItemStateChanged

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Trabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Modificar_Trabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbAntiguedad;
    private javax.swing.JComboBox cmbCargo;
    private javax.swing.JComboBox cmbDepartamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rdFemenino;
    private javax.swing.JRadioButton rdMasculino;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JFormattedTextField txtCedula;
    private javax.swing.JTextField txtID;
    private javax.swing.JFormattedTextField txtINSS;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JFormattedTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
