package Ventanas;


import Clases.Conexion;
import Clases.Trabajador;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FI23
 */
public class Ver_HrsExtras extends javax.swing.JFrame {

    /**
     * Creates new form Ver
     */
    public Ver_HrsExtras() {
        initComponents();
         Tabla.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbbuscar = new javax.swing.JComboBox();
        txtbuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Horas Extras");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.getTableHeader().setReorderingAllowed(false);
        Tabla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TablaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TablaFocusLost(evt);
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Buscar Por:");

        cmbbuscar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No.", "Trabajador", "Horas Extras", "Fecha", "Estado" }));

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        jButton1.setText("Mostar Todo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(2, 2, 2))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(679, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     DefaultTableModel model = new DefaultTableModel() {

    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
}; 
     
        public class FormatoTablaTrabajador extends DefaultTableCellRenderer
{
 @Override
 public Component getTableCellRendererComponent
 (JTable table, Object value, boolean selected, boolean focused, int row, int column)
 {
         
  if(String.valueOf(table.getValueAt(row,4)).equalsIgnoreCase("No Cancelado"))  {
      setForeground(Color.RED);
  }
   else { setForeground(Color.BLACK);
   }
  
          
    
 super.getTableCellRendererComponent(table, value, selected, focused, row, column);
 return this;
 }
 }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

       Tabla.setDefaultRenderer(Object.class, new FormatoTablaTrabajador());
        
        String [] Titulo = {"No","Trabajador", "Cantidad de Horas Extras", 
            "Fecha de Las Horas Extras", "Estado"};
        
        model.setColumnIdentifiers(Titulo);
        
        Tabla.setModel(model);
        
        MostrarTodo();
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MostrarTodo();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
Buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked

        
        if(evt.getClickCount()==2 && evt.getButton()==MouseEvent.BUTTON1){
        
            
        int index = Tabla.getSelectedRow();
        
        String ID, Nombre, Horas, Fecha;
        
        ID = (String) Tabla.getValueAt(index, 0);
        Nombre = (String) Tabla.getValueAt(index, 1);
        Horas = (String) Tabla.getValueAt(index, 2);
        Fecha = (String) Tabla.getValueAt(index, 3);
       
        
        
        
        Modificar_HorasExtras MH = new Modificar_HorasExtras();
        MH.setVisible(true);
            try {
                MH.Parametros(ID, Nombre, Horas, Fecha);
            } catch (ParseException ex) {
              
            }
        MH.setV(this);
        
        }
// TODO add your handling code here:
    }//GEN-LAST:event_TablaMouseClicked

    private void TablaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TablaFocusGained
       // TODO add your handling code here:
    }//GEN-LAST:event_TablaFocusGained

    private void TablaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TablaFocusLost
   // TODO add your handling code here:
    }//GEN-LAST:event_TablaFocusLost

    ResultSet resultado;
    
    public void MostrarTodo(){
        
        
        model.setRowCount(0);
        
       
            try {
                resultado = Conexion.consulta("Select * from [dbo].[HorasExtrasV]");
            
        
        while(resultado.next()){
           
            String [] Titulo = new String[5];
            
            String Nombres, Apellidos;
            
            Titulo [0] = String.valueOf(resultado.getInt(1));
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            Titulo [1] = Nombres.trim().concat(" ").concat(Apellidos.trim());
            Titulo [2] = String.valueOf(resultado.getInt(4));
            Titulo [3] = String.valueOf(resultado.getDate(5));
            Titulo [4] = resultado.getString(6);
            
            
            model.addRow(Titulo);
            
            
        }
        } catch (SQLException ex) {
                     
            JOptionPane.showMessageDialog(null, "Error Al Realizar Consulta"); 
            return; 
}
        Tabla.setModel(model);
           
        
    }
    
    
    public void Buscar(){
        
        
        int index = cmbbuscar.getSelectedIndex()+1;
        
        String Buscar = txtbuscar.getText();
        
     switch (index){
         
         case 1:
        
          model.setRowCount(0);
        
       
            try {
                resultado = Conexion.consulta("Select * from [dbo].[HorasExtrasV] where "
                        + "[ID_HrsExtras] like '%"+Buscar+"%'");
            
        
        while(resultado.next()){
           
            String [] Titulo = new String[5];
            
            String Nombres, Apellidos;
            
            Titulo [0] = String.valueOf(resultado.getInt(1));
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            Titulo [1] = Nombres.trim().concat(" ").concat(Apellidos.trim());
            Titulo [2] = String.valueOf(resultado.getInt(4));
            Titulo [3] = String.valueOf(resultado.getDate(5));
            Titulo [4] = resultado.getString(6);
           
            
            model.addRow(Titulo);
            
            
        }
        } catch (SQLException ex) {
                     
            JOptionPane.showMessageDialog(null, "Error Al Realizar Búsqueda"); 
            return; 
}
             break;
      
             
             
               case 2:
        
         model.setRowCount(0);
        
       
            try {
                resultado = Conexion.consulta("Select * from [dbo].[HorasExtrasV] where "
                        + "[Nombres_Trabajador]+' '+ [Apellidos_Trabajador] like '%"+Buscar+"%'");
            
        
        while(resultado.next()){
           
            String [] Titulo = new String[5];
            
            String Nombres, Apellidos;
            
            Titulo [0] = String.valueOf(resultado.getInt(1));
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            Titulo [1] = Nombres.trim().concat(" ").concat(Apellidos.trim());
            Titulo [2] = String.valueOf(resultado.getInt(4));
            Titulo [3] = String.valueOf(resultado.getDate(5));
            Titulo [4] = resultado.getString(6);
           
            
            model.addRow(Titulo);
            
            
        }
        } catch (SQLException ex) {
                     
            JOptionPane.showMessageDialog(null, "Error Al Realizar Búsqueda"); 
            return; 
}

             break;
                   
                case 3:
        
           model.setRowCount(0);
        
       
            try {
                resultado = Conexion.consulta("Select * from [dbo].[HorasExtrasV] where "
                        + "[HrsExtras] like '%"+Buscar+"%'");
            
        
        while(resultado.next()){
           
            String [] Titulo = new String[5];
            
            String Nombres, Apellidos;
            
            Titulo [0] = String.valueOf(resultado.getInt(1));
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            Titulo [1] = Nombres.trim().concat(" ").concat(Apellidos.trim());
            Titulo [2] = String.valueOf(resultado.getInt(4));
            Titulo [3] = String.valueOf(resultado.getDate(5));
            Titulo [4] = resultado.getString(6);
           
            
            model.addRow(Titulo);
            
            
        }
        } catch (SQLException ex) {
                     
            JOptionPane.showMessageDialog(null, "Error Al Realizar Búsqueda"); 
            return; 
}
         
             break;
                       
               
                case 4:
         model.setRowCount(0);
        
       
            try {
                resultado = Conexion.consulta("Select * from [dbo].[HorasExtrasV] where "
                        + "[Fecha] like '%"+Buscar+"%'");
            
        
        while(resultado.next()){
           
            String [] Titulo = new String[5];
            
            String Nombres, Apellidos;
            
            Titulo [0] = String.valueOf(resultado.getInt(1));
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            Titulo [1] = Nombres.trim().concat(" ").concat(Apellidos.trim());
            Titulo [2] = String.valueOf(resultado.getInt(4));
            Titulo [3] = String.valueOf(resultado.getDate(5));
            Titulo [4] = resultado.getString(6);
           
            
            model.addRow(Titulo);
            
            
        }
        } catch (SQLException ex) {
                     
            JOptionPane.showMessageDialog(null, "Error Al Realizar Búsqueda"); 
            return; 
}
         
             break;
                           
      
                case 5:
         model.setRowCount(0);
        
       
            try {
                resultado = Conexion.consulta("Select * from [dbo].[HorasExtrasV] where "
                        + "[Estado_Hrs] like '%"+Buscar+"%'");
            
        
        while(resultado.next()){
           
            String [] Titulo = new String[5];
            
            String Nombres, Apellidos;
            
            Titulo [0] = String.valueOf(resultado.getInt(1));
            Nombres = resultado.getString(2);
            Apellidos = resultado.getString(3);
            Titulo [1] = Nombres.trim().concat(" ").concat(Apellidos.trim());
            Titulo [2] = String.valueOf(resultado.getInt(4));
            Titulo [3] = String.valueOf(resultado.getDate(5));
            Titulo [4] = resultado.getString(6);
           
            
            model.addRow(Titulo);
            
            
        }
        } catch (SQLException ex) {
                     
            JOptionPane.showMessageDialog(null, "Error Al Realizar Búsqueda"); 
            return; 
}
         
             break;
                           
     
         
               
               default:break;      
        }
     
  
     
        Tabla.setModel(model);
           
        
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_HrsExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_HrsExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_HrsExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_HrsExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_HrsExtras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox cmbbuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
